### ISSUE TITLE
Can't resolve babel-loader

### ISSUE THREAD

**Issue by seanfisher** [tlovett1/alexa-skill-test#2] opened 2017-03-19 14:37 UTC
I installed the tool globally and when I run it in my lambda folder I get:

> sean$ alexa-skill-test
> Alexa Skill Test
> Skill: my-skill
> Open http://localhost:3000 in your browser
> Hash: 61f2d9554b289fa45f94
> Version: webpack 2.2.1
> Time: 45ms
>
> ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/Users/sean/prog/my-skill'
> webpack: Failed to compile.

The website comes up as a blank screen.

Any ideas? Does this library really require me to install babel-loader into my application for it to work?

**Comment by tlovett1** [comment] 2017-03-20 02:37
Hmmm I'm not able to reproduce. Can you debug?

**Comment by zzolo** [comment] 2017-04-10 02:01
I get the same thing.  I am using the library locally, instead of globally.

```
node v6.10.1
npm 3.10.10
```

**Comment by zzolo** [comment] 2017-04-10 02:07
So, if I install the module globally, it works.  I don't see anything that easily explains why this would behave this way.  It would be nice to install this locally and use something like `./node_modules/.bin/alexa-skill-test` to run it.

**Comment by alopix** [comment] 2017-05-18 20:14
I get something similar but with a lot of dependencies. I installed it globally though…

`ERROR in /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/traverseAllChildren.js
Module not found: Error: Can't resolve 'fbjs/lib/warning' in '/usr/local/lib/node_modules/alexa-skill-test/node_modules/reac
t-dom/lib'
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/traverseAllChildren.js 21:14-41
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/ReactChildReconciler.js
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/ReactMultiChild.js
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/ReactDOMComponent.js
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/ReactDefaultInjection.js
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/lib/ReactDOM.js
 @ /usr/local/lib/~/alexa-skill-test/~/react-dom/index.js
 @ /usr/local/lib/~/alexa-skill-test/src/index.js`

**Comment by acucciniello** [comment] 2017-06-21 14:46
I get the same thing here is my error message:
```
$ alexa-skill-test
Alexa Skill Test
Skill: alphabet-teacher
Open http://localhost:3000 in your browser
Hash: 61f2d9554b289fa45f94
Version: webpack 2.6.1
Time: 51ms

ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/Users/Antonio/Coding/alphabet-teacher'
webpack: Failed to compile.
```
it happens globally as well when trying to install and run locally.

I am using:
Node v8.0.0.0
Yarn 0.24.6

**Comment by gyandeeps** [comment] 2017-07-21 02:11
Had the same issue when i installed locally.

Temp solution

```sh
cd ./node_modules/alexa-skill-test
npm install
cd ../..
./node_modules/.bin/alexa-skill-test
```

This would work but its painful.

**Comment by tlovett1** [comment] 2017-07-23 20:09
Would love a fixing PR :/

**Comment by bencarter78** [comment] 2017-08-27 11:12
I was having the same issue and found the following to work for me (slightly different from @gyandeeps)

```
cd node/modules/alexa-skill-test
npm install
cd ../..
./node_modules/alexa-skill-test/bin/start.js
```

**Comment by tlovett1** [comment] 2018-04-11 03:56
This should be fixed now.

**Closed as completed by tlovett1** 2018-04-11 03:56 UTC

**Comment by daanzu** [comment] 2018-04-11 10:50
Had a similar problem involving bootstrap-sass just now with latest version. @gyandeeps solution solved it.
